// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omdqidanirajnlnhurwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tZHFpZGFuaXJham5sbmh1cnd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4MTY4NzMsImV4cCI6MjA3NzM5Mjg3M30.AG3l1vw2xiwne_kwq05q4UGIbV6sL_Zv1tqDkbhjhqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});